version: "3.9"
services:
  mongodb:
    container_name: mongodb
    image: mongo:latest
    networks:
      - microservice
    ports:
      - 27017:27017
    volumes:
      - db:/data/db
  dbredis:
    container_name: dbredis
    image: 'redis'
    networks:
      - redis
    ports:
      - 6379:6379
  app:
    container_name: app
    depends_on:
      - mongodb
      - dbredis
    build: .
    env_file: ./.env
    environment:
      - REDIS_HOST=dbredis
      - DB_HOST=mongodb
      - DB_NAME=$MONGODB_DATABASE
      - DB_PORT=$MONGODB_DOCKER_PORT
    volumes:
      - .:/usr/src/app
    ports:
      - 8080:8080
    networks:
      - microservice
      - redis

networks:
  microservice:
    name: microservice
  redis:
    name: redis
volumes:
  db:
    name: db
  redis:
    name: redis